spring:
  jpa:
    hibernate:
      ddl-auto: "update"
    database-platform: "org.hibernate.dialect.MySQL5InnoDBDialect"
  datasource:
    url: "jdbc:mysql://localhost:3306/disertatie"
    username: "root"
    password: ""
    driver-class-name: "com.mysql.jdbc.Driver"
  thymeleaf:
    cache: false